### ISSUE TITLE
Revert removal of return function type in `streamProbesWithOffsetFactory` when new scalafmt version is out

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-connectors-kafka#14]
In https://github.com/apache/incubator-pekko-connectors-kafka/pull/8 we removed the return function type because scalafmt has a bug with tuples as return function types in order to unblock the repo.

When a new version of scalafmt is out we should revert the change, just to be on the safe side to ensure that no important code has been changed from Akka latest Apache release.

**Comment by seglo** [comment]
In this case it's just a private test method so any risk is pretty minimal.

**Comment by mdedetrich** [comment]
Agreed, this is more about confidence wrt "the initial 1.0.x release has the same code as latest Akka BSL" even if its largely technically superficial with this case.
