### ISSUE TITLE
get tests to work with Scala 3

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-connectors-kafka#59]
* follow up to https://github.com/apache/incubator-pekko-connectors-kafka/pull/58
* that PR makes the code compile
* unfortunately something about the scala 3 generated classes upsets the Java jupiter test framework
* one option would be be to take the Java tests out of the 'tests' module and create a Java only 'java-tests' module
* we might still be able to run that java-tests module using sbt but we may be forced into using a Java build tool like maven or gradle

**Comment by He-Pin** [comment]
Any chance report this to dotty issues too？

**Comment by pjfanning** [comment]
scala 3 snapshots are now being published - https://repository.apache.org/content/groups/snapshots/org/apache/pekko/pekko-connectors-kafka_3/
